# Generated by Django 3.2.18 on 2023-03-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='student',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='student',
            name='graduated',
            field=models.BooleanField(default=True),
        ),
    ]
