# Generated by Django 3.2.18 on 2023-03-24 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
