# Generated by Django 3.2.18 on 2023-03-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mbti',
            field=models.CharField(choices=[('ENTP', 'ENTP'), ('ESFJ', 'ESFJ'), ('ISTJ', 'ISTJ'), ('INFP', 'INFP')], max_length=4),
        ),
    ]
